id: say_hi
namespace: company.team

tasks:
  - id: hi
    type: io.kestra.plugin.core.log.Log
    message: Hi!!!!!!!!!!!!!!!!!!!

triggers:
  - id: every_minute
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/1 * * * *"