name: Kestra CI/DC

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate:
    runs-on: ubuntu-latest
    name: Kestra validate
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Validate all flows on server-side
        uses: kestra-io/validate-action@master
        with:
          directory: ./_flows
          resource: flow
          server: http://34.116.118.43:8080
          user: ${{ secrets.KESTRA_USER }}
          password: ${{ secrets.KESTRA_PASSWORD }}

  # If validation passed, deploy resources
  deploy:
    runs-on: ubuntu-latest
    name: Kestra deploy
    steps:
      # We can only deploy to one namespace at once,
      # so we have two different steps for our two namespaces product and engineering
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Deploy company.team
        uses: kestra-io/deploy-action@master
        with:
          namespace: company.team
          directory: ./_flows
          resource: flow
          server: http://34.116.118.43:8080
          user: ${{ secrets.KESTRA_USER }}
          password: ${{ secrets.KESTRA_PASSWORD }}
          
      - name: Deploy zoomcamp
        uses: kestra-io/deploy-action@master
        with:
          namespace: zoomcamp
          directory: ./_flows
          resource: flow
          server: http://34.116.118.43:8080
          user: ${{ secrets.KESTRA_USER }}
          password: ${{ secrets.KESTRA_PASSWORD }}

